import { StyleSheet, Dimensions } from 'react-native';
import { lightColors, darkColors } from '../../theme/colors';

// Lấy kích thước màn hình để tính toán layout tốt hơn
const { width } = Dimensions.get('window');
const ScreenHeight = Dimensions.get('window').height;

export const createStyles = (isDarkMode: boolean) => {
  const colors = isDarkMode ? darkColors : lightColors;

  return StyleSheet.create({
    container: {
      flex: 1,
    },
    backgroundImage: {
      flex: 1,
      width: '100%',
      height: '100%',
    },
    safeAreaContainer: {
      flex: 1,
      paddingTop: 40, // For status bar
    },
    favoriteButtonContainer: {
      position: 'absolute',
      top:80,
      right: 20,
      zIndex: 10,
    },
    favoriteIconButton: {
      width: 44,
      height: 44,
      borderRadius: 22,
      backgroundColor: 'rgba(255, 255, 255, 0.2)',
      justifyContent: 'center',
      alignItems: 'center',
    },
    favoriteIconImage: {
      width: 24,
      height: 24,
      tintColor: '#fff',
    },
    topBar: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingHorizontal: 20,
      marginTop: 10,
    },
    heartButton: {
      width: 40,
      height: 40,
      justifyContent: 'center',
      alignItems: 'center',
    },
    heartIcon: {
      width: 28,
      height: 28,
      tintColor: '#fff',
    },
    progressContainer: {
      flex: 1,
      flexDirection: 'column',
      alignItems: 'center',
      marginHorizontal: 15,
    },
    progressText: {
      color: '#fff',
      fontSize: 16,
      fontWeight: '600',
      marginBottom: 5,
    },
    progressBar: {
      width: '100%',
      height: 4,
      backgroundColor: 'rgba(255, 255, 255, 0.3)',
      borderRadius: 2,
    },
    progressFill: {
      height: '100%',
      backgroundColor: '#fff',
      borderRadius: 2,
    },
    crownButton: {
      width: 40,
      height: 40,
      justifyContent: 'center',
      alignItems: 'center',
    },
    crownIcon: {
      width: 28,
      height: 28,
      tintColor: '#fff',
    },
    quoteContainer: {
      flex: 1,
      alignItems: 'center',
      paddingTop: ScreenHeight * 0.2,
      paddingHorizontal: 30,
    },
    quoteText: {
      fontSize: 36,
      color: '#fff',
      textAlign: 'center',
      fontWeight: '500',
      lineHeight: 46,
      fontFamily: 'Georgia',
      textShadowColor: 'rgba(0, 0, 0, 0.5)',
      textShadowOffset: { width: 1, height: 1 },
      textShadowRadius: 5,
    },
    bottomBar: {
      flexDirection: 'row',
      justifyContent: 'center',
      alignItems: 'center',
      paddingBottom: 20,
      marginBottom: 80, // Space for tab bar
    },
    shareButton: {
      width: 50,
      height: 50,
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: 'rgba(255, 255, 255, 0.2)',
      borderRadius: 25,
      marginHorizontal: 10,
    },
    shareIcon: {
      width: 24,
      height: 24,
      tintColor: '#fff',
    },
    favoriteButton: {
      width: 50,
      height: 50,
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: 'rgba(255, 255, 255, 0.2)',
      borderRadius: 25,
      marginHorizontal: 10,
    },
    favoriteIcon: {
      width: 24,
      height: 24,
      tintColor: '#fff',
    },
    tabBarPlaceholder: {
      position: 'absolute',
      bottom: 30,
      left: 0,
      right: 0,
      alignItems: 'center',
    },
    tabButton: {
      backgroundColor: '#fff',
      paddingVertical: 12,
      paddingHorizontal: 30,
      borderRadius: 25,
    },
    tabButtonText: {
      color: '#333',
      fontSize: 16,
      fontWeight: '600',
    },
    // Giữ lại các style cũ cho khả năng tương thích
    gradientBackground: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: colors.backgroundSecondary,
    },
    quoteCard: {
      width: width * 0.9,
      backgroundColor: isDarkMode ? '#2A2A2A' : colors.background,
      borderRadius: 25,
      padding: 25,
      shadowColor: isDarkMode ? '#000' : colors.text,
      shadowOffset: {
        width: 0,
        height: 4,
      },
      shadowOpacity: isDarkMode ? 0.5 : 0.1,
      shadowRadius: 8,
      elevation: isDarkMode ? 8 : 5,
      borderWidth: 1,
      borderColor: isDarkMode ? '#3A3A3A' : colors.border,
    },
    header: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 30,
    },
    categoryBadge: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: isDarkMode ? '#3A3A3A' : colors.backgroundSecondary,
      paddingVertical: 8,
      paddingHorizontal: 12,
      borderRadius: 20,
      borderWidth: 1,
      borderColor: isDarkMode ? '#4A4A4A' : colors.border,
    },
    categoryIcon: {
      fontSize: 20,
      marginRight: 8,
    },
    categoryName: {
      fontSize: 14,
      color: isDarkMode ? '#FFFFFF' : colors.text,
      fontWeight: '600',
    },
    nextButton: {
      backgroundColor: colors.primary,
      paddingVertical: 15,
      paddingHorizontal: 50,
      borderRadius: 25,
      alignItems: 'center',
    },
    nextButtonText: {
      color: isDarkMode ? '#FFFFFF' : colors.background,
      fontSize: 18,
      fontWeight: '600',
    },
    navigationContainer: {
      width: '100%',
      flexDirection: 'row',
      justifyContent: 'space-around',
      paddingHorizontal: 20,
      marginTop: 0,
      marginBottom: 10,
      position: 'absolute',
      bottom: 20,
    },
    navButton: {
      backgroundColor: 'white',
      paddingVertical: 15,
      paddingHorizontal: 40,
      borderRadius: 30,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.15,
      shadowRadius: 4,
      elevation: 3,
    },
    navButtonText: {
      color: '#466995',
      fontSize: 16,
      fontWeight: '500',
    },
    adBanner: {
      backgroundColor: 'rgba(255, 255, 255, 0.9)',
      padding: 12,
      borderRadius: 30,
      alignItems: 'center',
      marginTop: 40,
      width: 70,
      alignSelf: 'center',
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.1,
      shadowRadius: 2,
      elevation: 2,
    },
    adText: {
      fontSize: 14,
      color: '#7F8C8D',
    },
    menuButton: {
      position: 'absolute',
      top: 18,
      right: 18,
      zIndex: 20,
      backgroundColor: 'rgba(255,255,255,0.9)',
      borderRadius: 20,
      padding: 8,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      elevation: 3,
    },
    menuIcon: {
      fontSize: 24,
      color: '#466995',
      fontWeight: 'bold',
    },
    menuOverlay: {
      flex: 1,
      backgroundColor: 'rgba(0,0,0,0.15)',
      justifyContent: 'flex-start',
      alignItems: 'flex-end',
    },
    menuPopup: {
      backgroundColor: 'white',
      borderRadius: 16,
      marginTop: 60,
      marginRight: 18,
      paddingVertical: 8,
      width: 160,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.15,
      shadowRadius: 8,
      elevation: 8,
    },
    menuItem: {
      paddingVertical: 14,
      paddingHorizontal: 20,
    },
    menuItemText: {
      fontSize: 16,
      color: '#466995',
      fontWeight: '500',
    },
    bottomMenuWrapper: {
      position: 'absolute',
      bottom: 30,
      left: 0,
      right: 0,
      alignItems: 'center',
      zIndex: 30,
    },
    bottomMenuButton: {
      backgroundColor: 'white',
      borderRadius: 32,
      padding: 18,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.15,
      shadowRadius: 8,
      elevation: 8,
    },
    bottomMenuIcon: {
      fontSize: 32,
      color: '#466995',
      fontWeight: 'bold',
    },
  });
};

