import { StyleSheet, Dimensions } from 'react-native';

// Lấy kích thước màn hình để tính toán layout tốt hơn
const { width } = Dimensions.get('window');

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#E8F4FD',
  },
  gradientBackground: {
    flex: 1,
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingTop: 30,
    paddingBottom: 30,
  },
  quoteCard: {
    backgroundColor: 'white',
    borderRadius: 20,
    width: width * 0.9,
    paddingHorizontal: 20,
    paddingTop: 20,
    paddingBottom: 30,
    alignItems: 'center',
    justifyContent: 'flex-start',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 8,
    marginTop: 50,
    marginBottom: 40,
    minHeight: 350,
  },
  header: {
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
  },
  categoryIcon: {
    fontSize: 24,
    color: '#E74C3C',
  },
  shareIcon: {
    fontSize: 24,
    color: '#5DADE2',
  },
  quoteContent: {
    width: '100%',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 10,
    minHeight: 80,
  },
  quoteText: {
    fontSize: 22,
    color: '#466995',
    textAlign: 'center',
    lineHeight: 30,
    fontWeight: '600',
    flexWrap: 'wrap',
    maxWidth: '100%',
  },
  favoriteContainer: {
    position: 'relative',
    alignItems: 'center',
    justifyContent: 'center',
    marginVertical: 10,
    width: 70,
    height: 70,
    marginBottom: 10,
  },
  favoriteBackground: {
    position: 'absolute',
    width: 70,
    height: 70,
    borderRadius: 35,
    backgroundColor: 'white',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.15,
    shadowRadius: 5,
    elevation: 6,
  },
  favoriteButton: {
    width: 70,
    height: 70,
    borderRadius: 35,
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 1,
  },
  favoriteIcon: {
    fontSize: 30,
    color: '#BDC3C7',
  },
  favoriteIconActive: {
    color: '#E74C3C',
  },
  nextButton: {
    backgroundColor: '#4A90E2',
    paddingVertical: 14,
    paddingHorizontal: 60,
    borderRadius: 30,
    marginTop: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 4,
    alignSelf: 'center',
  },
  nextButtonText: {
    color: '#FFFFFF',
    fontSize: 18,
    fontWeight: '600',
  },
  navigationContainer: {
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'space-around',
    paddingHorizontal: 20,
    marginTop: 0,
    marginBottom: 10,
    position: 'absolute',
    bottom: 20,
  },
  navButton: {
    backgroundColor: 'white',
    paddingVertical: 15,
    paddingHorizontal: 40,
    borderRadius: 30,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 4,
    elevation: 3,
  },
  navButtonText: {
    color: '#466995',
    fontSize: 16,
    fontWeight: '500',
  },
  adBanner: {
    backgroundColor: 'rgba(255, 255, 255, 0.9)',
    padding: 12,
    borderRadius: 30,
    alignItems: 'center',
    marginTop: 40,
    width: 70,
    alignSelf: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
  },
  adText: {
    fontSize: 14,
    color: '#7F8C8D',
  },
  menuButton: {
    position: 'absolute',
    top: 18,
    right: 18,
    zIndex: 20,
    backgroundColor: 'rgba(255,255,255,0.9)',
    borderRadius: 20,
    padding: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  menuIcon: {
    fontSize: 24,
    color: '#466995',
    fontWeight: 'bold',
  },
  menuOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.15)',
    justifyContent: 'flex-start',
    alignItems: 'flex-end',
  },
  menuPopup: {
    backgroundColor: 'white',
    borderRadius: 16,
    marginTop: 60,
    marginRight: 18,
    paddingVertical: 8,
    width: 160,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 8,
  },
  menuItem: {
    paddingVertical: 14,
    paddingHorizontal: 20,
  },
  menuItemText: {
    fontSize: 16,
    color: '#466995',
    fontWeight: '500',
  },
  bottomMenuWrapper: {
    position: 'absolute',
    bottom: 30,
    left: 0,
    right: 0,
    alignItems: 'center',
    zIndex: 30,
  },
  bottomMenuButton: {
    backgroundColor: 'white',
    borderRadius: 32,
    padding: 18,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 8,
  },
  bottomMenuIcon: {
    fontSize: 32,
    color: '#466995',
    fontWeight: 'bold',
  },
});

