require_relative "../node_modules/react-native/scripts/react_native_pods"

platform :ios, min_ios_version_supported
prepare_react_native_project!
workspace "DailyBoostApp.xcworkspace"

target "DailyBoostApp" do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|    
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )

    # Force C++20 for safety
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings["CLANG_CXX_LANGUAGE_STANDARD"] = "c++20"
      end
    end
  end
end
